RECEIVER_EMAIL = "<YOUR_EMAIL_ADDRESS>"
APP_PASSWORD = "<YOUR_APP_PASSWORD>"
KUCOIN_API_KEY = '<YOUR_KUCOIN_API_KEY>'
KUCOIN_API_SECRET = '<YOUR_KUCOIN_API_SECRET>'
KUCOIN_API_PASSPHRASE = '<YOUR_KUCOIN_API_PASSPHRASE>'
